const loginForm=document.querySelector('#login-form');const passwordForm=document.querySelector('#password-form');const dashboard=document.querySelector('#dashboard');const message=document.querySelector('#login-message');const passwordMessage=document.querySelector('#password-message');
function csrf(){const item=document.cookie.split('; ').find(value=>value.startsWith('__Host-aionui-portal-csrf='));return item?decodeURIComponent(item.split('=').slice(1).join('=')):''}
async function request(path,options={}){const headers=new Headers(options.headers||{});if(options.body)headers.set('Content-Type','application/json');const token=csrf();if(token)headers.set('X-CSRF-Token',token);const response=await fetch(path,{...options,headers,credentials:'same-origin'});if(!response.ok)throw new Error(await response.text());return response.json()}
function showUser(user){loginForm.classList.add('hidden');dashboard.classList.remove('hidden');document.querySelector('#welcome').textContent=`${user.username}，欢迎回来`;document.querySelector('#tenant-id').textContent=user.tenant_id;request('/api/policy').then(policy=>document.querySelector('#policy-id').textContent=policy.policy_id).catch(()=>document.querySelector('#policy-id').textContent='暂不可用')}
request('/api/session').then(data=>showUser(data.user)).catch(()=>{});
loginForm.addEventListener('submit',async event=>{event.preventDefault();message.textContent='正在验证…';try{const data=await request('/api/login',{method:'POST',body:JSON.stringify({username:document.querySelector('#username').value,password:document.querySelector('#password').value})});document.querySelector('#password').value='';message.textContent='';showUser(data.user)}catch(error){document.querySelector('#password').value='';message.textContent='用户名或密码不正确，或登录暂时受限。'}});
document.querySelector('#show-password-change').addEventListener('click',()=>{document.querySelector('#change-username').value=document.querySelector('#username').value;loginForm.classList.add('hidden');passwordForm.classList.remove('hidden');passwordMessage.textContent=''});
document.querySelector('#cancel-password-change').addEventListener('click',()=>{passwordForm.reset();passwordForm.classList.add('hidden');loginForm.classList.remove('hidden');passwordMessage.textContent=''});
passwordForm.addEventListener('submit',async event=>{event.preventDefault();passwordMessage.textContent='正在修改…';const body={username:document.querySelector('#change-username').value,current_password:document.querySelector('#current-password').value,new_password:document.querySelector('#new-password').value,confirm_password:document.querySelector('#confirm-password').value};try{await request('/api/password/change',{method:'POST',body:JSON.stringify(body)});document.querySelector('#username').value=body.username;passwordForm.reset();passwordForm.classList.add('hidden');loginForm.classList.remove('hidden');message.textContent='密码已修改，请使用新密码登录。';passwordMessage.textContent=''}catch(error){passwordMessage.textContent='密码修改失败，请检查当前密码和新密码要求。'}finally{body.current_password='';body.new_password='';body.confirm_password=''}});
document.querySelector('#logout').addEventListener('click',async()=>{try{await request('/api/logout',{method:'POST'})}finally{location.reload()}});
